from turtle import *
pd()
goto(20,20)
setx(50)
circle(50,180,7)
dot(50,'red')
speed(0.6)
color("blue")
j=stamp()
lt(90)
fd(50)
i=stamp()
shape("turtle")
fd(50)
print(pen())
write('海龟', move=True, align="left", font=("Arial", 8, "normal"))
fd(50)
fd(50)
fd(50)
text=textinput("NIM", "Name of first player:")
textinput(text, text)
